language: python
python:
- '2.7'
install:
- pip install ansible molecule apache-libcloud
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
env:
  global:
  - secure: A4rgayJ7Pin9LJRmswsHDHaaYDyp54f1gNiyAs0oOxvcWpQq6BG8s9Dqdsh8TaI1uY/b+R9+reP5uBAzUYiDD7LYqjl73VdTCK4MvhaLg9XNXEbJZuCrpZuCENtuQgV019Pb1ja0gl87RQx4m7PUPKRn7TY5H15CdSfIUK9W9NEjKcd4L8M+RyB3eO53VI9827XQNbNYS+Srb1Q9bBI+cf5KM1WF1/cax539MIE6QyLi6GFGmGCsPD0Z3J855B7wloFzamti9gfRP/ozpvd4lG6J8fmoGlsfHNOhdXjrU5vrTg7lKeEmPdNM+t5kTjFrp762DOjwo9so3qqOYkOEajnR+Q/RNH31ezMzLzFZPpan30twN/7MHXKxIFLSRQMYrCsRnim62MAGFGFVweKyq9QfiGZnJEqTDr6FBdEf7/Yxa+CX1gfYMLz7RpEi/gknJ090zHS1iwrXdo838AvxSuluB5tXOoGuJ9+/2DWOBIr5MmW/aEulQtslTDhZiMWST9GnDWWrUNWspRyNIA8AEBMQFYOC6wgUCnK5SG3muQAANN5MvjF5nTzypzS5OF0PYV/axq1lkLi32RvAhXGw1s+Xkh4AP67XV2yAuN1bAHn8gAVKnUcVlD5Mqw9BADTM6BDYMGKBxxLStc5ahzoad/FAJn2nT2RKxaosjuMyob4=
  - secure: hRKkMsqaPp8NjO5YVctniHJH8tjJCo4aLFF/E+NX6BqF4iEAexKzbXP8XWeuiKV47jo14S1mYjVMrMZi8GpijDUQ2/bYcX2GMfl+1UJiJeaaxcK1SDeBYuaYksYwYn5vtCXlotIWATYx4yKYB4fszJ7va/5mklrMwMlpBX0MoFyIcsVaucjB5AYea1O9BvWcL5ZHOxPaUm3S1TX+93t+AHwGIIdkk+2R3CYy0DYqL6+buDpFgNq4rwdmppq5xBcPy2pev4LJJhiRLVCSUa/qPg+KCyXY3HkWFXwlF99SLg2b1pB9uQcC7o4rfa/2WHuVlAygEDzsEVURImvEcUec2pcIkDSHijQwfGBWmVRFvKZR0mbC4P4ZXTnVxo3Pr57DF1e2Q0+qaH+/eUpHA4BWvGTeud74BPicgc9qapywUihGxfpZbikmDHHZpZ0kiBJGk2F0qpEUN5/QqHzwNgyLcNgGptWJ9ulYc32ZdYfg4fzeSESRcmzYjcPR4b+WJ810ov0oejeMUjgdMF80opKe5dRQfy2v1NSStPJVXLNvZVgyBshhqCz90SCVDmkq1njZQflt961pLPKuE2Er0mL1alp1SIjVjn0y+iAYkSzyERVBozHa9imvuYMQ6//GWS3cHdZRttTQ3wOb83tGWbN5eZ0dihmRH9q63XTK5Q597qg=
dd:
  secure: OyBoJi91HMSEg25inD0DX4F9Nw+FsdLH/pTtliR4vJV1wJzPPSNAEw3QE7ecbPt2+X8y6jF3OfjnvjgPs+cT5aHzyExWW3GO1q79TNMs3C8ll0WvppcP6oom6ERJIJRBWXMGKt+kxhhr3+yiaGTBPijmtiGEjYsebPzdtBCe6AmTMzNhFTLnHsLaU0C2ZOnmCqY+Y5NoYMGYvC3YjtT1dulE+0Jnw96SysgiLIU3S69kbvismRVSSDUvqiQJmT0sIACM1lLU3Jr3vGLnQyj4PUSS4hJWDzaSmmWhRpHsD7QVHFXvhPY+V7D/Y4kg+1/CBdh/RGa5FLtrPid/nw5zvPwC6aJE65HoEthSg1Yfsgbes59oh6P0WfN4+FXKOnMlmXMKrXPkvLM4FX1PaZ/zDD4yJpWxmWmkSfIBV9o7Q44XwHWDaPRz362GnbEJmHSvJubNjw19JbhYov206fWnSwb2paCdvwcczlYJdlc+duWdvWqCc1A9eBjOUMpYNvUNeJZ7f6Sb+PBIlVyfvzBe9a9mKnaOz/+gLpw81N3DjGyGcioPE+9Zw+VXeWEdC3w6hPcCzKMO8JIgS0EDEWSmcSI1nsmeVQrRUvVZHrIE7MfMp8Wy0TZIqlaZ5bEx+M8vb6O8MRHz9iWcCen+t/wLVNdPx23HdpT351cBYkjsqDE=
before_install:
- openssl aes-256-cbc -K $encrypted_061848cd5ae6_key -iv $encrypted_061848cd5ae6_iv
  -in secrets.tar.enc -out secrets.tar -d
