language: python
python:
- '2.7'
install:
- pip install ansible molecule apache-libcloud
script:
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
after_script:
- molecule destroy
env:
  matrix:
    - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: oCKVWs4o5Pt17WWTRWUEvQuVi+Vqs/axeGTclsm79nBCn2tckZUVd4kLi/4NzrrRnmydKFWIzdwgyhzaH9sHz3IKMuuvSoyXJpWRQFt0fy4gZAbRXdO6+i6z+IHp3TCvsUAAD63Iw2XfTmQ1sauf04AQc3QmGbHxrn8iJmryYTaMgLsCwfZ5MOyntpZlI3TICwg0/WcTxvBieE/CXQYPXhckXOtFMaSEsvJeFnddxXAHY7iYSsb2qxwpZY9eBViYinsNYbs2Vn0eAp+0eP+rz2gvrleXyM6AOa7/Cdi75QL1GDBBxan68XaxyUah+xlzchptteurNdFDzsCh6VF+MuNkoVvkDihwOzecZ//d0zhn1dwjbNTy6yfY+jtHFACoQNAn6OfERexJ5W/+1bcyk53bcM/gDIbqLjqWv6vA+1Nmd8hdL5GAREjPFMTulho7TfxKRRtSvoxiXcFF5jx9+JEixvuLXmymrVXMUgOF6GomYOCUUeMJHyN4JpSwEoPeH1LqQIy/cfGPTGQyFk7PLRKMkU7P0/cen29Q1SLgKQ3RVTPYUeaW2GuAXV0I/I5XlSGCrOcoZbz/iICv07o4Kgp6qiL45Cms9fNYhiACi7V4FS0r6vdnyvR8/lprNzmEoWn3cBiJ6kYmtVUhcE5roGdgRf8FCAuu4oOG8K1iWVM=
  - secure: CLX9uWvZgdNsKP0TeMkCodk2gg48JyOFqiJQM7d82jJV0u6l01NudwkrecEJjtqE0uGVcMQlmucwhLtfLbHf/534uvBzDHJKyJVoJWVq3CU4ZnN6dSmsbglv8mHwL2DLZpqefOysVNOFrtcuq1DT0af4/rlGjw9DouI2xQjU9FY5V/iyqZugMmBDhb53p3+RJ+zL/0FbKk2iipH0Xbale2AhKG6A0GTu51C52GyNc0bYLRVIBNEU/xmvcc2oBUJ5DF1kePuCwGYkRziunXDEMq8l8iN0vad5crFnWQCKv988GHBg+Z4dKGvF+rbZyx1UPnaJSqsee/wA3wHaxvtLIhTRrHsusr9Ru+iJwLMp5Gh5eUCbHNL2SWJ9HSGBKJT3Hr/46wwZ3QA24lbrLGrbIrgXm8likTA1xnMRmn6I1ODcHavnwcdr7B5XvvwVR01r0DnSvas7cWmNT1k+iQ4qXxXiFsoG2IGVrjG1jRj8jtNUp7RiDaFd9c2/BbOXFl/jq2GSYAEuW287+eR7v4nXJc78xAhtcOmLt0iKhMbd+f23tMMkp1GGfZs/7F7/5fr6ChZ+jZQiL0tHq/CIXEFRWwSOKAH/8dQR6XL+6hgA9YIKGrgcH4XJZN/5l5l/v7pXpB/5xhYEe4bXd8BAKchNfevsRht5R2MLh3NqFdWo45s=
#  - secure: JiywKAznevUguL1WQEW9r3PDIkbrLZ/zs8D7FbuC2vyKs36bOh2dEnuXXtqg6iz/0v8cK8VISZGD0eOOoxhbjy0J2w8jKXB7iG/1JIn12s3octIcK+V3pjvcmS+TD6fQnAvqTvc5b7RLp8gaDq8qGE7tlm87JDV2VBb9giCXZJhM0/z4LntdzRC+KrG6qDo2z6JxnnfUETXkM/47LodYv28/qCqJBtVITRKOlYOqL1kv2DkB7m6OTJmw0j05iek0hYKZRPsUisaPqeqv0e8HsR3CK5qbKXgz9RkKDyFTpiY1rku7D3UiV4EDtsCgabmErVUH/T1PoxrTqgLCOvIhX83G0hcURxLQ1HnNKNKKCXrdq2edzsoKgI9zWBgF5kUpOF5BNGRbMBjv8Pe75eXF4lWTxcqLRbVHnH8fPV8Mr4uKOoSqjlVq9mSfEhrYGkO0dhNWPDHCHrM/I9L2VsTX79qGoeMR+ZLCNouQrQyIfKFy9ETcT9KPHlHL0trT3jwMPUmHDtchZsgeTIqJsFK3/Z0iqQydc6eh4rnltJZ6ey357UR9beou2T5O4OCPyHTVqkIad9JpMckZpz/8EHEE7CPCA2agh2efFBkC2crCIZ9RmeLrCyFhFca1vlIFCmbbCloOy/HAdahPbmywhiax6G5J+FGXVnq0Uq+NXwIvnuY=
before_install:
- openssl aes-256-cbc -K $encrypted_061848cd5ae6_key -iv $encrypted_061848cd5ae6_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
