---
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
  tags: packer-mongo

- name: Add mongodb repository into sources list
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: packer-mongo

- name: Install mongodb-org from repo
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  tags: packer-mongo

- name: Enable service mongod
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: packer-mongo
